### ISSUE TITLE
OptView usage improvements

### ISSUE THREAD

**Issue by johnjasa** [mdolab/pyoptsparse#10]
Add an option to only show variables/functionals with bounds to more easily see which are constraints

**Comment by nwu63** [comment]
@johnjasa has this been addressed?

**Comment by johnjasa** [comment]
No, this specific issue has been addressed. I forget what conversation this came out of, as well. Do you think this feature would be useful, @nwu63? @nbons?

**Comment by nbons** [comment]
I think it could be useful, but certainly not necessary.

**Comment by nwu63** [comment]
Oh I see this is about showing/hiding certain outputs in optview. Since we have the obj/constraint names stored in the `info` tags, this shouldn't be too bad to implement. I will prioritize other items before this though.

**Comment by nwu63** [comment]
Closing as OptView is in low maintenance mode.
