### ISSUE TITLE
Default pyIPOPT.py settings fail when building using doc instructions

### ISSUE THREAD

**Issue by bbrelje** [mdolab/pyoptsparse#12]
When building IPOPT / pyIPOPT with the default instructions (including ma27 as the linear solver), the default set of run options in pyIPOPT.py fails (MUMPS is the default linear solver). Changing mumps to ma27 fixes the problem. The tests will run (and fail).

**Comment by nwu63** [comment]
@bbrelje can you confirm that #33 addresses this?

**Comment by bbrelje** [comment]
@nwu63 Yes
