### ISSUE TITLE
Using SNOPT binaries

### ISSUE THREAD

**Issue by jdebecdelievre** [mdolab/pyoptsparse#124]
Hi all,

I am trying to use the binary SNOPT file, and installed everything as described in the last FAQ question (https://ccom.ucsd.edu/~optimizers/docs/snopt/faqs.html) which links to this page: https://gist.github.com/gnowzil/b1ea867a8808a3b3b759881ce8369ad2

When I try the following:
```
from pyoptsparse import Optimization, OPT

def fun(x):
    return {'obj':x['x']**2}, False

problem = Optimization('tmp', fun)
problem.addVar('x', lower=0.)
problem.addObj('obj')
opt = OPT('SNOPT', options={})
sol = opt(problem, sens='fd')
```

I get:
```
capi_return is NULL
Call-back cb_snlog_in_snoptc__user__routines failed.
Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    sol = opt(problem, sens='fd')
  File "/Users/jeandebecdelievre/soft/pyoptsparse/pyoptsparse/pySNOPT/pySNOPT.py", line 489, in __call__
    snopt.snkerc(start, nnCon, nnObj, nnJac, iObj, ObjAdd, ProbNm,
ValueError: unexpected array size: new_size=1, got array with arr_size=0
```

Is there something else that needs to be changed to use SNOPT binaries with pyoptsparse?
Thanks!
Jean

**Comment by nwu63** [comment]
Hi Jean, please follow the pyOptSparse documentation to compile SNOPT for use with pyOptSparse, which is different from the standalone installation process detailed in the link you provided, since pyOptSparse has to invoke f2py together with the Fortran source code to compile a Python library.

Furthermore, note the requirements and supported platforms in the documentation. For example, we currently only support SNOPT v7.7.x, along with a Linux OS.

**Comment by jdebecdelievre** [comment]
Hi Neil,
Thank you for your quick reply.
I should be good with the requirements you mentioned (snopt 7.7 and linux).
Binary files can be easier to get by for things like class projects (students can get the snopt binary files with a 3months licence). I was wondering whether pyoptsparse could work with the standalone installation. 
Do you think that I stand a chance, or is the code setup such that the fortran code is required ? (as your reply above seems to imply)
Thanks!

**Comment by nwu63** [comment]
The Fortran source code is absolutely required, in order to compile a Python interface via `f2py`. There is no way to directly use a compiled binary in Python as far as I'm aware, and in any case we have settled on using `f2py` to do the linking.
