### ISSUE TITLE
Check default optimizer options

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#135]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- New feature (non-breaking change which adds functionality)

## Description
The default options stored in the Python wrapper is probably out of date for those optimizers that are still being developed. Check against newest versions and update as necessary.

Also, the behaviour is different across optimizers
- for some optimizers, the default options are used (e.g. IPOPT)
- for others, the default options are not used (e.g. SNOPT, ParOpt)

We need a clear policy on what exactly we are doing, and document this. I think we should NOT store/set defaults for optimizers where we do not provide source code, since they can change defaults at any time and cause inconsistencies with the wrapper. For those optimizers where we provide the source code, we should have the default options accessible in Python, and documented (via options table).

Lastly, there may be default options where we override them in pyOptSparse (think certain options in SNOPT for example). These need to be documented and explained.

**Comment by eirikurj** [comment]
@sseraj @nwu63 Was this issue supposed to be closed by #188? It seems from the issue description that it applies to all optimizers. Have all of them been verified?

**Comment by nwu63** [comment]
Yep I did verify everything. Taken from the description of #188:

>  I also checked that other optimizers are using the default values, and that the documentation is consistent with the code.

So far everything is consistent, but I have also opened two issues related to this for future improvement.
