### ISSUE TITLE
SLSQP sol.optInform doesn't return exit code

### ISSUE THREAD

**Issue by andrewtrainor** [mdolab/pyoptsparse#137]
## Type of issue
What types of issue is it?
- Bugfix (non-breaking change which fixes an issue)

## Description
I have been comparing aspects of different solvers and for the 'SLSQP' solver when I run sol.optInform it returns {}. For the other solvers that I have used in there it returns a code and a breif descriptions in a dictionary but for slsqp it returns an empty one.

### Steps to reproduce issue
1. run SLSQP and use sol.optInform after problem solve.

**Comment by nwu63** [comment]
I have found the problem and will push a fix soon.

**Comment by andrewtrainor** [comment]
great thanks!

**Comment by nwu63** [comment]
For future reference, you should leave the issue open until it's addressed. In this case, once the PR is merged it should automatically close this issue. Thanks for bringing this to our attention btw.

**Comment by andrewtrainor** [comment]
good to know thanks!
