### ISSUE TITLE
Changing maximum iterations

### ISSUE THREAD

**Issue by andrewtrainor** [mdolab/pyoptsparse#139]
## Type of issue
What types of issue is it?
Potential bug in pyoptsparse.

## Description
I am trying to increase the maximum iterations for the IPOPT solver for a problem that I am working on. from the docs I understand that to do that you would write:

optOptions = {"max_iter": 400}

When I did that it still gave the maximum iterations exceeded at 100 iterations. Did I try implementing that correctly?

**Comment by nwu63** [comment]
I just tested this and everything works fine. Are you sure you are passing this options dictionary to the `options=` argument when calling `OPT`?

**Comment by andrewtrainor** [comment]
This is how I have it implemented in the equation. It sounds like I put it in incorrectly.

def opt_constrained(guess):
    n = len(time)
    tolerance = 1.0e-4
    optProb = pyoptsparse.Optimization('Apex-Rhino', Ebalance)
    optProb.addVarGroup('gen', n, value=guess[:n],
                        lower=np.zeros(n), upper=np.ones(n)*config['capacity'])
    optProb.addVarGroup('tes_store', n, value=guess[n:2*n],
                        lower=np.ones(n)*-1, upper=np.ones(n))
    optProb.addConGroup('max_ramp', n, upper=config['max_ramp_rate'])
    optProb.addConGroup('tes_T', n, lower=config['tes_min_t'], upper=config['tes_max_t'])
    optProb.addConGroup('tes_max_dT', n, upper=config['tes_dTmax'])
    optProb.addConGroup('EnergyBal', n, upper=tolerance, lower=-1*tolerance)

    optProb.addObj('obj')
    print('Problem', optProb)
    optOptions = {"max_iter":400}
    opt = pyoptsparse.OPT('IPOPT')
    sol = opt(optProb, sens='FD')  # 'FD', 'FDR', 'CD', 'CDR'
    return sol

**Comment by nwu63** [comment]
You need to pass the options dictionary to pyOptSparse, otherwise it's just a random dictionary that you've defined in your run script. See [here](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/quickstart.html) for an example, where the `IPRINT` option is modified.

**Comment by andrewtrainor** [comment]
Thanks for the help!
