### ISSUE TITLE
SNOPT 7.6 won't build with v1.2

### ISSUE THREAD

**Issue by achase90** [mdolab/pyoptsparse#154]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

x Bugfix (non-breaking change which fixes an issue)

## Description
I've been trying to install pyoptsparse [v1.2](https://github.com/mdolab/pyoptsparse/releases/tag/v1.2) with SNOPT v7.6 and can't get it to compile. I've removed the snopth.f file from src and pasted the rest of the files into pySNOPT/source. It breaks on sn70nobj.o

Any ideas how I can debug this? Output is [here](https://github.com/mdolab/pyoptsparse/files/5125386/output2.txt).

### Code version (if relevant)
Python 3.7.3

Package                            Version             Location
---------------------------------- ------------------- -------------------------------------------------------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.3
apipkg                             1.5
appdirs                            1.4.3
applaunchservices                  0.2.1
appnope                            0.1.0
appscript                          1.1.1
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.1.post1
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.4
Babel                              2.8.0
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
baron                              0.9
beautifulsoup4                     4.9.1
bitarray                           1.5.2
bkcharts                           0.2
bleach                             3.1.5
bokeh                              2.1.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cachetools                         3.1.1
certifi                            2020.6.20
cffi                               1.14.0
chardet                            3.0.4
click                              7.1.2
click-completion                   0.5.2
cloudpickle                        1.5.0
clyent                             1.2.2
cmake                              3.13.3
colorama                           0.4.3
conda                              4.8.4
conda-build                        3.17.8
conda-package-handling             1.7.0
conda-verify                       3.1.1
contextlib2                        0.6.0.post1
coverage                           4.5.4
crayons                            0.3.0
cryptography                       2.9.2
cv                                 1.0.0
cycler                             0.10.0
Cython                             0.29.15
cytoolz                            0.10.1
dash-interactive-graphviz          0.1.1
dask                               2.20.0
DateTime                           4.3
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
dill                               0.2.9
distributed                        2.20.0
docutils                           0.16
dymos                              0.13.0
entrypoints                        0.3
et-xmlfile                         1.0.1
execnet                            1.6.0
fastcache                          1.1.0
fenics                             2019.1.0
fenics-dijitso                     2019.1.0
fenics-ffc                         2019.1.0.post0
fenics-fiat                        2019.1.0
fenics-ufl                         2019.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fortranformat                      0.2.5
fsspec                             0.8.0
future                             0.18.2
geographiclib                      1.49
geopy                              1.19.0
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.0.8
gobject                            0.1.0
google-api-python-client           1.7.11
google-auth                        1.6.3
google-auth-httplib2               0.0.3
google-auth-oauthlib               0.4.1
graphviz                           0.13.2
greenlet                           0.4.16
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
httplib2                           0.14.0
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
iniconfig                          0.0.0
intervaltree                       3.0.2
ipy-table                          1.15.1
ipykernel                          5.3.4
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyterlab                         2.1.5
jupyterlab-server                  1.2.0
keyring                            21.2.1
kiwisolver                         1.2.0
latexcodec                         1.0.7
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
MarkupSafe                         1.1.1
matplotlib                         3.3.1
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.4.0
mpi4py                             3.0.3
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
multiprocess                       0.70.7
multiprocessing-logging            0.2.6
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
nbstripout                         0.3.5
netgraph                           3.1.6
networkx                           2.4
nltk                               3.5
nose                               1.3.7
notebook                           6.1.1
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.19.1
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
opencv-python                      4.2.0.34
opencv-utils                       0.0.2
openmdao                           3.1.1
openpyxl                           3.0.4
oset                               0.1.3
packaging                          20.4
pandas                             1.1.0
pandocfilters                      1.4.2
parameterized                      0.7.0
parso                              0.7.0
partd                              1.1.0
path                               14.0.1
pathlib2                           2.3.5
pathos                             0.2.3
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
petsc4py                           3.11.0
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.2.2
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
pox                                0.2.5
ppft                               1.6.4.9
prometheus-client                  0.8.0
prompt-toolkit                     3.0.5
protobuf                           3.7.1
psutil                             5.7.0
ptyprocess                         0.6.0
py                                 1.9.0
pyasn1                             0.4.7
pyasn1-modules                     0.2.6
pybtex                             0.22.2
pybtex-docutils                    0.2.1
pycairo                            1.18.2
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.5
pycycle                            0.0.8
pydocstyle                         5.0.2
pyDOE2                             1.3.0
pydot                              1.4.1
pyflakes                           2.2.0
Pygments                           2.6.1
PyGObject                          3.30.5
pygraphviz                         1.5
PyJWT                              1.7.1
pylint                             2.5.3
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyoptsparse                        2.1.5
pyparsing                          2.4.7
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             6.0.1
pytest-forked                      1.0.2
pytest-timeout                     1.3.3
pytest-xdist                       1.28.0
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.34.1
pytz                               2020.1
PyWavelets                         1.1.1
PyYAML                             5.3.1
pyzmq                              19.0.1
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.5
QtPy                               1.9.0
readme-renderer                    24.0
redbaron                           0.9.2
regex                              2020.7.14
requests                           2.24.0
requests-oauthlib                  1.2.0
requests-toolbelt                  0.9.1
rope                               0.17.0
rply                               0.7.7
rsa                                4.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
SchemDraw                          0.6.0
scikit-image                       0.16.2
scikit-learn                       0.23.1
scikit-umfpack                     0.3.2
scipy                              1.5.2
seaborn                            0.10.1
Send2Trash                         1.5.0
setuptools                         49.6.0.post20200814
shellingham                        1.3.2
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.15.0
smt                                0.3.4
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-bibtex               0.4.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.4
spyder-kernels                     1.9.2
SQLAlchemy                         1.3.18
sqlitedict                         1.6.0
statsmodels                        0.11.1
sympy                              1.6.1
tables                             3.6.1
tblib                              1.7.0
terminado                          0.8.3
testflo                            1.4.1
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.48.2
traitlets                          4.3.3
twilio                             6.44.2
twine                              1.13.0
typed-ast                          1.4.1
typing-extensions                  3.7.4.2
ujson                              1.35
unicodecsv                         0.14.1
uritemplate                        3.0.0
urllib3                            1.25.10
uuid                               1.30
varName                            0.0.1
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
wrapt                              1.11.2
wurlitzer                          2.0.1
wxPython                           4.0.5
xdot                               1.1
xlrd                               1.2.0
XlsxWriter                         1.2.9
xlwings                            0.19.5
xlwt                               1.3.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     5.1.0

**Comment by nwu63** [comment]
Hi! So, we don't officially support 7.6 since we have no access to that version of SNOPT. I took a quick look at the log you posted and I didn't see anything notable. Something happens during the gfortran stage and not the f2py stage, so I don't think it's anything to do with numpy even though I think we've had issues with 1.19 in the past. Not really sure, the log doesn't even show what the error was. Are you on a Mac? That adds another level of complexity to building these codes.

So, since we can't replicate the error and we don't support 7.6, I'm not sure what help we can offer. Building SNOPT on its own should definitely work without any problems, so you should try to get to that stage first. Then, it's possible that some function signatures changed between 7.6 and 7.7, and that you need to modify the f2py interface file yourself to be able to link it to pyOptSparse.

**Comment by achase90** [comment]
Thanks for the help, it pointed me down compiling SNOPT itself. There's a type mismatch in SNOPT source. I added
```
export FCFLAGS="-w -fallow-argument-mismatch -O2"
export FFLAGS="-w -fallow-argument-mismatch -O2"
```
mentioned [here](https://github.com/Unidata/netcdf-fortran/issues/212#issuecomment-638457375) to my environment prior to pip installing and it works! Thanks again.
