### ISSUE TITLE
Investigate installing SNOPT separately

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#155]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Maintenance

## Description
As described in the [SNOPT FAQ](https://ccom.ucsd.edu/~optimizers/docs/snopt/faqs.html#other-issues), it's possible to compile SNOPT separately and then link to pyOptSparse without having to move source files around. Investigate this approach and see if we want to adopt the `setup.py` modifications and install SNOPT in a standalone fashion.

**Comment by marcomangano** [comment]
@nwu63 we tried this for the latest 7.7 release and found out there were not clear advantages.. can this be closed?

**Comment by nwu63** [comment]
Yeah I seem to remember this, let's just close this.
