### ISSUE TITLE
PSQP and CONMIN not working for unconstrained problems

### ISSUE THREAD

**Issue by peterrohl** [mdolab/pyoptsparse#157]
## Type of issue
What types of issue is it?

Bug
## Description
wrappers for CONMIN and PSQP pass incorrectly formatted variables to FORTRAN code for unconstrained problems.
In addition, it appears that both methods also need the "dummy Constraint" as implemented in SLSQP as the code tries to access a constraint variable that doesn't exit (which the introduction of the dummy constraint fixes).

I attached modified code for pyCONMIN.py and pyPSQP.py that fix the problems
### Steps to reproduce issue
1. Run attached test script implementing Rosenbrock's function (modified from pyOpt test script)
2. …
3. …

### Current behavior
Python throws an error message when calling the FORTRAN wrapper. Once that's fixed, non-existent variable "gcon" causes another error (fixed with the introduction of the dummy constraint)

### Expected behavior
no error

### Code version (if relevant)
**Python version:** 3.7

[bugfix.zip](https://github.com/mdolab/pyoptsparse/files/5198120/bugfix.zip)

**Comment by nwu63** [comment]
Hey, thanks for opening this issue, and actually fixing it! Would you mind opening a corresponding PR? Then we can go through the review process and make sure the fix is good, before merging the code.

**Comment by peterrohl** [comment]
> Hey, thanks for opening this issue, and actually fixing it! Would you mind opening a corresponding PR? Then we can go through the review process and make sure the fix is good, before merging the code.

No problem. I am just not sure what I need to do as I am new to this process.

**Comment by nwu63** [comment]
Are you familiar with using `git` and GitHub? Basically, what you need to do is
- fork pyOptSparse on GitHub
- create a branch locally
- commit your changes to that branch
- push to your fork on GitHub
- submit a pull request to this repository

[This page](https://guides.github.com/activities/forking/) might help. Let me know if anything's not clear.

**Comment by peterrohl** [comment]
I don't think our corporate firewall will allow me to do that. We are basically not allowed to exchange files with the outside world, except for downloading through a web browser

**Comment by peterrohl** [comment]
Even to upload the sample code I attached to the issue, I had to get off the VPN and connect to the internet directly, which I can do when I work from home, but technically, that's no allowed

**Comment by nwu63** [comment]
I see, not a problem we'll go through the code you attached and make a PR from that. Will message you if we run into any problems.

**Comment by peterrohl** [comment]
Just diff the code. I only changed a few statements. Every change is marked with my initials (PR)
