### ISSUE TITLE
Improve skipTest handling

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#177]
# Description of feature
Sometimes when testing we expect all the optimizer to be available (such as Travis tests on master), and even on PR builds we want specific tests to pass and others to skip. The way that is done currently, sometimes tests will essentially fail silently, if some optimizer wasn't installed properly it's simply skipped instead of reported as a failure.

# Potential solution
This is currently done with the skipTest stuff in unittest. Maybe we want some sort of conditional skip with the `skipIf` decorator, and specify some environment variable to specify that all tests must pass.

A harder task would be to specify a list of optimizers that are expected to be available, so that we can test the PR builds correctly as well without manually checking the list of skipped tests.

**Comment by marcomangano** [comment]
@nwu63 [this baseclasses PR](https://github.com/mdolab/baseclasses/pull/52) is paving the way to address this issue, right? Is it something that we want to prioritize?

**Comment by marcomangano** [comment]
Did [the test refactoring](https://github.com/mdolab/pyoptsparse/pull/251) fix this? I don't recall it now but I don't want to lose track of this again

**Comment by nwu63** [comment]
This was addressed in #237.
