### ISSUE TITLE
IPOPT history recording

### ISSUE THREAD

**Issue by kanekosh** [mdolab/pyoptsparse#182]
## Description
Objective and constraint calls are recorded duplicately.
When the optimizer evaluates the objective and constraint at a point `x`, it should be recorded as a single iteration. But it seems that it is recorded as two iterations with the same variable/function values.

### Steps to reproduce issue
Run any constrained problem, then check the number of function calls printed in `IPOPT.out` as well as the iterations in the OptView plot.

### Current behavior
For example, when `IPOPT.out` says it finished after 100 objective evaluations and 100 constraint evaluations, we see 200 iterations in the OptView plot as a result of the duplication.

### Expected behavior
We should have just 100 iterations in the plot.

**Comment by A-Gray-94** [comment]
@kanekosh , I just discovered this issue for myself, did you ever figure out a possible fix?

**Comment by kanekosh** [comment]
This bug occurs because [the IPOPT wrapper](https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pyIPOPT/pyIPOPT.py#L201) defines callback functions for objective(`eval_f`) and constraints (`eval_g`) separately, unlike other optimizers which define one function that returns both. Each callback wraps [_masterFanc](https://github.com/mdolab/pyoptsparse/blob/d1aea3688589815ab05b5b4b3686b093957850c0/pyoptsparse/pyOpt_optimizer.py#L198) in which we record the history. So at each point `x`, IPOPT calls `_masterFuncs` twice (once for objective, once for constraints) and duplicates the log.

We may want to unify the two callbacks into one (such as `eval_f_g`) as other optimizers do. But it needs a (major) update of the C codes.

Another way is to add the `writeHist = True/False` argument to `_masterFunc`, and enable it only from the `eval_f`. Then we don't record the history from the `eval_g` and can avoid duplication. This is just at python level and easy to do, but I'm not sure if it's a good fix.

**Comment by A-Gray-94** [comment]
I don't think it's a good idea to rely on modifying how IPOPT makes evaluation calls as then we'd essentially be maintaining our own version of IPOPT no? Seems much easier to just handle it in the python layer

**Comment by kanekosh** [comment]
Right we shouldn't be touching the IPOPT codes. I'm just not sure if we need to modify IPOPT itself or just our C wrappers (like pyipoptcoremodule.c).

**Comment by kanekosh** [comment]
Never mind, I thought `pyipoptcoremodule.c` and other stuff are our own code, but it was a misunderstanding. I'll submit a python-layer fix soon.

**Comment by A-Gray-94** [comment]
FYI, it looks like this has been an issue for quite a while, check out these IPOPT and GCMMA plots from our [aero shape optimisation benchmark paper](https://www.sciencedirect.com/science/article/pii/S1270963817314475?via%3Dihub) back in 2017

![image](https://user-images.githubusercontent.com/20371123/116019688-c898a080-a612-11eb-9d20-c4b18e57e5b6.png)
