### ISSUE TITLE
HS71 test fails with ParOpt

### ISSUE THREAD

**Issue by A-Gray-94** [mdolab/pyoptsparse#195]
## Description
`test_hs071.py:TestHS71.test_paropt` currently fails due to a very small discrepancy in the optimum. Maybe Paropt settings have changed slightly since this test was trained?

### Steps to reproduce issue
Run the test suite:

`testflo . -v`

### Current behavior
Test fails due to ~1e-6 error in optimum point:

```
Mismatched elements: 1 / 2 (50%)
Max absolute difference: 1.30937905e-06
Max relative difference: 8.10918838e-06
 x: array([ 0.552294, -0.16147 ])
 y: array([ 0.552294, -0.161469])
```

### Expected behavior
Test should pass

### Code versions
Up to date master branches of pyoptsparse and Paropt as of Jan 26th 2021

**Comment by sseraj** [comment]
[We only support (and test) ParOpt v2.0.2](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/optimizers/ParOpt.html ). That's still the latest ParOpt release. Have there been any changes since that release that you need?

**Comment by nwu63** [comment]
@A-Gray-94 can you confirm that the ParOpt release v2.0.2 works as expected?

**Comment by A-Gray-94** [comment]
Sure, will do later today

**Comment by A-Gray-94** [comment]
Yep, works fine with v2.0.2, weird. Closing
