### ISSUE TITLE
Problems building with SNOPT

### ISSUE THREAD

**Issue by michK** [mdolab/pyoptsparse#20]
Good day,

I am having trouble building with SNOPT on Ubuntu 18.04.

With both pyoptsparse/ and snopt7/ in my home directory, my procedure is:

```
cd ~/pyoptsparse
cp ~/snopt7/src/*.f pyoptsparse/pySNOPT/source/
python setup.py build
```
This results in the error:

```
Error: Symbol ‘ne’ at (1) has no IMPLICIT type
error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -I/home/michael/anaconda3/lib/python3.6/site-packages/numpy/core/include -c -c pyoptsparse/pySNOPT/source/snopth.f -o build/temp.linux-x86_64-3.6/pyoptsparse/pySNOPT/source/snopth.o" failed with exit status 1
```
Hoping that the build might still have worked, I added the following to my .bashrc:

`export PYTHONPATH=$PYTHONPATH:~/pyoptsparse/build/lib.linux-x86_64-3.6`

Starting Python it seems like the build somewhat worked, since running

`import pyoptsparse`

gives:

```
/home/michael/pyoptsparse/build/lib.linux-x86_64-3.6/pyoptsparse/pyOpt_MPI.py:50: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
```
This is odd since I do have mpi4py installed, but for now I am not worried about mpi4py. Importing pyoptsparse.pySNOPT runs without error. However, running `pyoptsparse.pySNOPT.SNOPT()` gives:

```
AttributeError: module 'pyoptsparse.pySNOPT' has no attribute 'SNOPT'
```

I would appreciate any help with this. Thanks in advance.

**Comment by JustinSGray** [comment]
You need to remove the snopth.f file from the source directory. Something is wonky from that file and it messes up the compilation when its in pyopt sparse.

**Comment by michK** [comment]
Great, that seems to have done the trick, thanks.

**Comment by sunyuping917** [comment]
https://ccom.ucsd.edu/~optimizers/docs/snopt/faqs.html

**Comment by nwu63** [comment]
> [ccom.ucsd.edu/~optimizers/docs/snopt/faqs.html](https://ccom.ucsd.edu/~optimizers/docs/snopt/faqs.html)

@sunyuping917 can you elaborate on that? What are you trying to say?

**Comment by sunyuping917** [comment]
Please see the following from https://ccom.ucsd.edu/~optimizers/docs/snopt/faqs.html#other-issues
I want to use pyOptSparse, but it requires the source code for SNOPT. Can I use the SNOPT precompiled libraries with pyOptSparse?

Yes, but you need to make a modification to pyOptSparse. The modification to the file pyoptsparse/pyoptsparse/pySNOPT/setup.py is available here. You will need to appropriately define the location of the SNOPT library and re-build/install pyOptSparse. Make sure you have also set DYLD_LIBRARY_PATH (on macOS) or LD_LIBRARY_PATH (on Linux) to the location of the SNOPT library and also make sure to set up the SNOPT license.

**Comment by nwu63** [comment]
I see. To be clear, this is not the recommended way to install pyOptSparse with SNOPT, and we do not test pyOptSparse with this approach.

**Comment by sunyuping917** [comment]
I regard this way is excellent as it decouples two codes, and it works. It is just my opinion. I will try your way.

**Comment by nwu63** [comment]
I agree, this is a nice way if you can reliably get it to work. In the future, we may change `pyOptSparse` to this approach, which is consistent with how we handle several other optimizers such as IPOPT.
