### ISSUE TITLE
History File Structure

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#25]
Just wanted to open an issue discussing what information should be included in the history file. Keeping the structure backwards compatible, it'd be nice to add a few more entries, such as timing information for each major iteration (which will have to be figured out in conjunction with #21). In addition, for benchmarking it would be useful for me to save `nprocs` but that could be done in my own fork.

Would it make sense to incorporate some of this into the main repo or would this clutter up the file too much?

**Comment by johnjasa** [comment]
I support adding this information and more. We won't have any concerns about backwards compatibility, I think, but we will need to make sure everything that's recording in the file is documented well.

Perhaps in the actual history file we also have a dictionary of keys with explanations for each entry in the history file.

**Comment by nwu63** [comment]
Do you know the reason why gradient evaluations are stored with separate `callCounter`'s even though it's at the same point? Would it make sense to have them stored under the same `callCounter`? That way we might be able to achieve some sort of consistency with ADflow output numbering.

**Comment by johnjasa** [comment]
I am not sure why this is the case, but I also haven't dug into it. @gkenway might be able to answer.

**Comment by nwu63** [comment]
After discussing with Eirikur, we decided to modify the structure by including a `info` or `metadata` tag, which would include items such as `nprocs`, `startTime`, `endTime`, and `optOptions`. Hopefully this would store enough information regarding the optimization that by viewing it the user can figure out exactly which case/setting it was.

**Comment by eirikurj** [comment]
Addressed in #77, closing.
