### ISSUE TITLE
How can I add the mma/gcmma solver into the pyoptsparse?

### ISSUE THREAD

**Issue by qwefhajk** [mdolab/pyoptsparse#260]
The pyopt support the mma/gcmma solver and I wonder how to add these solvers into pyoptsparse?

**Comment by nwu63** [comment]
We do not support MMA/GCMMA and there are no immediate plans to add support for these. Note that GCMMA as implemented in pyOpt does not actually contain the optimizer, which is proprietary and must be obtained separately.

**Comment by qwefhajk** [comment]
Then may I ask how can I add the GCMMA into pyOpt? I only have the matlab version of GCMMA and the pyOpt has not been updated for a long time.

**Comment by nwu63** [comment]
We are not affiliated with pyOpt and as you said that project is no longer maintained. My guess is that the MATLAB scripts are not compatible with pyOpt anyways so I'm afraid you are out of luck if you absolutely have to use GCMMA. Perhaps you can try one of the optimizers which are available?

**Comment by nwu63** [comment]
I'm going to close the issue, but feel free to comment if there's any follow up.
