### ISSUE TITLE
More flexible configurations for building IPOPT

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#262]
# Description of feature
Right now, we hard-code the libraries when building IPOPT: `libraries=["ipopt", "coinmumps", "coinmetis", "dl", "m", "blas", "lapack"]` but the user may wish to use other linear solvers for example.

# Potential solution
We could rely on certain environment variables that are set at build time to change these flags without having to modify `setup.py`. I don't have a good idea on what the naming scheme should be, though.

**Comment by whophil** [comment]
I believe only `ipopt` is required (assuming `ipopt` is compiled as a shared lib), as none of the pyIPOPT source files directly depend on methods from these libraries.

This issue is related:
https://github.com/xuy/pyipopt/issues/39
