### ISSUE TITLE
Why skip objFun when serializing Optimization?

### ISSUE THREAD

**Issue by whophil** [mdolab/pyoptsparse#264]
I have a `Optimization` with a very cheap `objFun` and am using `concurent.futures` to solve multi-starts in parallel. I've noticed that the `Optimization` arrives on the executor side without its `objFun`.

This is due to the following:
https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pyOpt_optimization.py#L1785

Is there a particular reason the `objFun` is skipped in the serialization of `Optimization`? Perhaps not every function is picklable, but some are.

Proposal: Test if `objFun` can be pickled; put it into the state dict if it can.

**Comment by nwu63** [comment]
For simple functions you can absolutely serialize them, but this becomes problematic when the function involves calling compiled libraries etc. I think what you're suggesting makes a lot of sense, we can try to open a PR soon but we'll have to test against our codes first to make sure it doesn't break anything.
