### ISSUE TITLE
Implementing hybrid algorithm

### ISSUE THREAD

**Issue by michK** [mdolab/pyoptsparse#29]
Good day,

I am trying to implement a hybrid algorithm where I first run a number of iterations
with the NSGA2 algorithm, and then I want to hot start either SNOPT or SLSQP
with the top performer from NSGA2.

I am able to set this up so that SNOPT/SLSQP reads the history file from NSGA2
for a hot start. This is running, but it seems that it is just reading the last history file generated
which is not necessarily the top performer from NSGA2.

Any suggestions on how to do this would be greatly appreciated.
Thanks

**Comment by michK** [comment]
**Update**

Followup to my previous question:

I noticed that the pyoptsparse solution class inherits from the optimization class, meaning that a solution object can be passed to a new problem. If I do this, will the new problem take the final/best solution of the previous solution for it's initial guess value?

If this is the case, this would be easier than the hot starting approach my original question refers to.

Thanks again
Michael

**Comment by johnjasa** [comment]
Hey Michael,

I understand what you're trying to do, and I'm not certain if the functionality exists natively in PyOptSparse at the moment. I would suggest writing a helper function or using some logic to find the best NSGA2 solution, then passing that as the initial condition for the next optimization problem.

As you mention, `pyOpt_solution` seems to have the capability to take in an `Optimization` object as commented here: https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pyOpt_solution.py#L6 but I don't know if that uses the final or best solution, which is different in NSGA2's case.

I'll ping @gkenway , the main developer of this code, to see if he can shed light on it.

**Comment by michK** [comment]
Hi John,

Thank you very much.

If I know that there isn't a built-in method to do it, I think it shouldn't be too hard to just implement myself as you suggest.

Cheers!
Michael
