### ISSUE TITLE
Unable to install with pyPSQP subpackage

### ISSUE THREAD

**Issue by Tarnarmour** [mdolab/pyoptsparse#297]
## Description

I'm trying to get pyoptsparse built from source on a windows 10 computer, running an anaconda installation of python 3.9.7. Following the instructions from the website, I've cloned the project. If I try to pip install, the installation fails. While searching for the cause of the failure I tried only installing some subpackages, and found by trial and error that as long as I commented out the subpackage installing for PSQP my installation succeeds.

I'm sorry I'm a bit new at this so if there is any other helpful information just let me know, I'm not sure what is most useful to include right now.

I've attached the error message.
[installation_output.txt](https://github.com/mdolab/pyoptsparse/files/8535682/installation_output.txt)

**Comment by nwu63** [comment]
Hey, thanks for letting us know, but as mentioned in the [docs](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/install.html#building-from-source),  we do not support installations under Windows. If it works for you and you don't need PSQP (which we haven't found to be very useful anyways) then I think you're all set.

**Comment by Tarnarmour** [comment]
Closing because as stated in docs, pyoptsparse is not supported on windos. I was unable to get pyoptsparse working; it reported a successful install but had problems compiling optimizers.

**Comment by nwu63** [comment]
FYI there is an ongoing effort to get a windows build working in #300, you can try that out to see if it works for you.
