### ISSUE TITLE
pyOptSparse Error: There was an error importing the compiled slsqp module

### ISSUE THREAD

**Issue by rcruzf99** [mdolab/pyoptsparse#306]
Hi all, 

When trying to run the airfoil_opt.py in the tutorials files of the MACH-Aero, the following error appears:
+------------------------------------------------------------------------------+
| pyOptSparse Error: There was an error importing the compiled slsqp module    |
+------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "airfoil_opt.py", line 265, in <module>
    opt = OPT(args.opt, options=optOptions)
  File "/home/bolseiros/.local/lib/python3.8/site-packages/pyoptsparse/pyOpt_optimizer.py", line 975, in OPT
    return opt(*args, **kwargs)
  File "/home/bolseiros/.local/lib/python3.8/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 35, in __init__
    raise Error("There was an error importing the compiled slsqp module")
pyoptsparse.pyOpt_error.Error: There was an error importing the compiled slsqp module

- Operating System: Linux
- Python: 3

Hope someone can help. Thank you

**Comment by marcomangano** [comment]
Hello,
It looks like the shared libraries were not compiled correctly, but it is hard to figure out what is wrong from this little information. Make sure you have the latest version of pyoptsparse and build it from scratch, removing any `build` or `meson_build` folder and older `.so` files.

This [comment](https://github.com/mdolab/pyoptsparse/issues/231#issuecomment-818845490) might give you some useful debugging tip.

**Comment by rcruzfardilha99** [comment]
Thank you! It worked!
