### ISSUE TITLE
Some problems about multipointSparse

### ISSUE THREAD

**Issue by NWPU-XuChenzhou** [mdolab/pyoptsparse#31]
Good day, John.
Sorry for disturbing you. I'm a PhD student from NWPU. I have already installed "MDOlab code" you uploaded several days ago. These codes are really helpful for me.  I followed MACH Tutorial to learn to use these codes. The example for ADflow analysis, illustrated in http://mdolab.engin.umich.edu/docs/packages/machtutorial/doc/aero_adflow.html,  was tested successfully in my own PC. I used 1core and 4 cores to run aero_run.py respectively, and it appeared all right. However, when I ran aero_opt.py, some problems occurred. First, the multipoint package was not open source, so there was an error because the python script imported module multipoint.

> xcz@ubuntu:~/Desktop/ADflow_test/opt_wing$ python aero_opt.py 
> Warning:` OpenMDAO dependency is not installed. OM_ADFLOW wrapper will not be active
> Traceback (most recent call last):
>   File "aero_opt.py", line 14, in <module>
>  from multipoint import *
> _No module named multipoint

For all the aero_opt or aerostruct_opt cases in the tutorial, the scripts import module multipoint.  Hence, I commented out the lines with multipointSparse in aero_opt.py myself, and modified the script with no reference script.  Then I got a problem with MPI erroror after ADflow finished in the process.

......
writetecplotsurfacesolution': True}
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

[1]PETSC ERROR: ------------------------------------------------------------------------
[1]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[1]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[1]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
......

 I have added my script in the attachment. Could you help me to modify my script? BTW, will the multipoint package be open source soon? Thanks a lot. 

[aero_opt.py.txt](https://github.com/mdolab/pyoptsparse/files/3130317/aero_opt.py.txt)

**Comment by johnjasa** [comment]
Hey there, thanks for your comments. To better track this issue, could you please repost it in the [ADflow repo](https://github.com/mdolab/ADflow)? Someone should be able to help you there. Thanks!
