### ISSUE TITLE
Numpy 1.24 compatibility

### ISSUE THREAD

**Issue by robfalck** [mdolab/pyoptsparse#317]
## Description

Numpy 1.24 has been released and removed a number of previous deprecations.
While instances of `numpy.float` were replaced with `float` in #287, but there are a handful of  `numpy.int` usages that are still problematic.

### Steps to reproduce issue

1. Any test involving slsqp, when run with numpy 1.24, will fail.

### Current behavior

Executing an OpenMDAO optimization using the latest version of pyoptsparse with SLSQP results in

```
  File "/Users/rfalck/opt/miniconda3-x86/envs/py310_x86/lib/python3.10/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 207, in __call__
    lw = np.array([lwM], np.int)
  File "/Users/rfalck/opt/miniconda3-x86/envs/py310_x86/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```

### Expected behavior

Replacing usages of `numpy.int` with `int` will resolve the issue.

### Code versions

- Operating System: OS X, Ubuntu, Windows
- Python: 3.10
- OpenMPI: N/A
- CGNS: N/A
- PETSc: N/A
- Compiler: N/A
- This repository:

**Comment by sseraj** [comment]
Thanks for opening this issue. I will take care of this soon.
