### ISSUE TITLE
setup.py build_ext --inplace returns file 'none'

### ISSUE THREAD

**Issue by ehariton** [mdolab/pyoptsparse#326]
## Description
Unable to install with `build_ext --inplace` on current master build. Previous builds: `0914abf94f47e26bfbdd36cc83436d7fda5f2c04` from March 6th 2022 did not have this issue.

### Steps to reproduce issue

```
git clone git@github.com:mdolab/pyoptsparse.git
python setup.py build_ext --inplace
```

### Current behavior
```
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    run_meson_build()
  File "setup.py", line 33, in run_meson_build
    p1 = subprocess.run(sysargs, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/home/skithuno/miniconda3/envs/mdaowork/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/skithuno/miniconda3/envs/mdaowork/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/skithuno/miniconda3/envs/mdaowork/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'None'
```

### Expected behavior
Installs without failing. 
Known working commits that does not fail:
`0914abf94f47e26bfbdd36cc83436d7fda5f2c04`
`5f9e836c246dcb8fab62688b5fcc0e023c96c551`

### Code versions

- Operating System: WSL 1.0 (Windows Subsystem For Linux)
- Python: Python 3.8.12
- OpenMPI:
- CGNS:
- PETSc:
- Compiler:
- This repository: `656fce2b27eb57aafd9a227a2d99d16e8616ccb3`

pip freeze
certifi==2021.10.8
charset-normalizer==2.0.12
coverage==4.5.4
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
-e git+https://github.com/OpenMDAO/dymos.git@9ae8ea2ca826c51b800efe8bda54b1f4badcc56f#egg=dymos
fonttools==4.25.0
kiwisolver @ file:///opt/conda/conda-bld/kiwisolver_1638569886207/work
matplotlib @ file:///tmp/build/80754af9/matplotlib-suite_1645455682260/work
mdolab-baseclasses==1.6.1
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186064646/work
mkl-service==2.4.0
mpi4py==3.1.3
munkres==1.1.4
networkx==2.7.1
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1634095647912/work
-e git+https://github.com/OpenMDAO/OpenMDAO.git@2e22ef7a4cefa6bd26072aa85b069a286aeb9667#egg=openmdao
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
Pillow==9.0.1
plotly==5.6.0
pyDOE2==1.3.0
pyoptsparse==2.7.0
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
-e git+https://github.com/mdolab/pyXDSM.git@259f56a0e455612dccaa3a12c77f5f79acdfad4e#egg=pyXDSM
requests==2.27.1
scipy==1.8.0
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1644875935023/work
sqlitedict==2.0.0
tenacity==8.0.1
testflo==1.4.8
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
urllib3==1.26.8

**Comment by sseraj** [comment]
We moved to a Meson build system in v2.9.0, which is what is causing this error. I don't think there is an equivalent build command with Meson.

Is there a reason `pip install -e .` does not suit your needs? This will build the optimizers and install pyOptSparse in place.

**Comment by nwu63** [comment]
Yeah the instructions have been changed from `python setup.py ...` to `pip` since v2.1.0 so it has not been a supported installation method since 2020.

**Comment by ehariton** [comment]
We've been using `build_ext --inplace` because it allows us to copy in the SNOPT source files and then run `python setup.py install`. This is the standard process we've been using for the last 4 years to run SNOPT in WSL (windows subsystem for linux).

**Comment by sseraj** [comment]
Our recommended approach is to copy the SNOPT source files into `pyoptsparse/pySNOPT/source` and then run `pip install -e .`

I have installed SNOPT this way on WSL.

**Comment by ehariton** [comment]
I'll give this a go and report back.

**Comment by ehariton** [comment]
> Our recommended approach is to copy the SNOPT source files into `pyoptsparse/pySNOPT/source` and then run `pip install -e .`
> 
> I have installed SNOPT this way on WSL.

This works fine. I did have to install a compiler first. 
Full instructions on how to get pyoptsparse + SNOPT working on WSL located here:
https://github.com/ehariton/BASH_SNOPT_install
