### ISSUE TITLE
pyOPTsparse and NLPQLP

### ISSUE THREAD

**Issue by KarthikComposites** [mdolab/pyoptsparse#380]
Hello,

I am trying to get a license for NLPQLP. As I understand, the latest version that pyOPTsparse supports is v4.2.2. However, v4.2.2 is not distributed anymore, while the later versions are available. Can a later version of NLPQLP be configured with pyOPTsparse? Looking for some inputs here. Below is the changelog:

C 4.22 (Dec, 2014) - iteration counter, output
C 4.23 (Feb, 2015) - NP check
C 5.0 (Sep, 2015) - all format statements collected at
C the bottom of this file for easier
C modification, identifiers cleaned
C 5.01 (Dec, 2016) - Documentation of NP
C 5.02 (Apr, 2017) - Copyright note, bug in error label
C 5.03 (Jan, 2020) - Length of integer working array

Thanks very much

**Comment by eirikurj** [comment]
Hi, at the moment the only supported and tested version is v4.2.2. However, this is not to say that newer versions may not work. The attached changelog is very brief, but as long as the NLPQLP interface has not changed, the current wrapper should work. I suggest you try this and if the source code compiles, you can use the [tests](https://github.com/mdolab/pyoptsparse/tree/main/tests) for testing the newer version.  We are interested in supporting newer versions, so please keep us posted on your findings.
