### ISSUE TITLE
Error while importing pyoptsparse

### ISSUE THREAD

**Issue by AbhijithMoni** [mdolab/pyoptsparse#387]
### Steps to reproduce issue

`from pyoptsparse.pySLSQP import slsqp`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "packages/pyoptsparse/pyoptsparse/__init__.py", line 3, in <module>
    from .pyOpt_history import History
  File "packages/pyoptsparse/pyoptsparse/pyOpt_history.py", line 12, in <module>
    from .pyOpt_utils import EPS
  File "packages/pyoptsparse/pyoptsparse/pyOpt_utils.py", line 23, in <module>
    from .types import ArrayType
  File "packages/pyoptsparse/pyoptsparse/types.py", line 9, in <module>
    NumpyType = Union[float, npt.NDArray[np.float64]]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'

### Code versions
v2.10.2 Latest
- Operating System: Linux
- Python: 3.9.5
- Numpy: 1.20.3
- CGNS: 4.3.0 
- PETSc: 3.15.1

**Comment by marcomangano** [comment]
Hi Abhijith,
this looks like a numpy version issue. We don't test numpy 1.20.x anymore (see our supported versions  [here](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/install3rdPartyPackages.html)), upgrading to numpy 1.21.x should fix this.

**Comment by AbhijithMoni** [comment]
@marcomangano Thanks, Marco. The issue has been resolved.

**Comment by nwu63** [comment]
@marcomangano we should probably update the version specification in `setup.py` though, perhaps following NEP29?

**Comment by marcomangano** [comment]
> @marcomangano we should probably update the version specification in `setup.py` though, perhaps following NEP29?

I think something like NEP29 should be set as a standard over the whole codebase (stay tuned for that), but for now I will open a quick PR to update the minimum numpy version.
