### ISSUE TITLE
fsqp not building on windows

### ISSUE THREAD

**Issue by dykesk** [mdolab/pyoptsparse#4]
I found this old PR that still seems open:
https://bitbucket.org/mdolab/pyoptsparse/pull-requests/27/add-conda-recipe/diff

I was able to build pyoptsparse in my windows conda environment but I had to comment out references to fsqp to do so; not sure if this is a known issue already

**Comment by rensmacneill** [comment]
I also have this issue on mac OS10.13.x. I can't import ffsqp or nlpqlp.

**Comment by mftatfcyclone** [comment]
I also have this issue on Windows 10 x64

**Comment by nwu63** [comment]
Apologies for neglecting stale issues. To be clear, we only support Linux installations at this time. If you made some tweaks to the code to make it work for a specific OS, and it's straightforward to test/maintain, then please feel free to submit a PR and we could potentially include additional OS support in the future.
