### ISSUE TITLE
No parallel computing feature for pyALPSO

### ISSUE THREAD

**Issue by zdmay** [mdolab/pyoptsparse#45]
Hello,

I'd like to run the pyOptSparse pyALPSO module and utilize a parallel environment.

I could do this in pyOpt by instantiating an ALPSO optimizer with the keyword argument "pll_type":

>from pyOpt import ALPSO
> alpso_dpm = ALPSO(pll_type='DPM')

I'd then execute my analysis with multiple processors using the mpirun command. 

Is this capability no longer supported in pyOptSparse for either pyALPSO or pyNSGA2?

Thank you very much for your time

**Comment by AOE-khkhan** [comment]
I am following this. Cause I used pyOpt. But Can anyone confirm me that what is happening with this?

**Comment by nwu63** [comment]
Have you tried the option `parallelType`? Setting it to `EXT` in the options should allow for parallel executions. However, ALPSO is in minimal maintenance mode, and this feature is not currently tested, so if it is broken then we do not plan on fixing it.
