### ISSUE TITLE
SNOPT internal finite differencing and parallel computing of gradients 

### ISSUE THREAD

**Issue by zdmay** [mdolab/pyoptsparse#46]
Hello,

I have a working version of pySNOPT in pyOptSparse, and I'd like to compute the gradients in parallel while using SNOPT's internal finite differencing method.

>from pyoptsparse import SNOPT
>snopt = SNOPT(sens=None,sensMode='pgc')

However, allocating more processors does not result in a reduction of runtime. Can pyOptSparse only compute gradients in parallel if you are using one of its built in finite difference methods? For example:

>snopt = SNOPT(sens='CS',sensMode='pgc')

Thank you very much for your time

**Comment by nwu63** [comment]
Hello @zdmay,

Exactly, SNOPT is a serial code and therefore you will not see a speedup. The `pgc` mode is for the pyOptSparse implementation of finite differences since pyOptSparse can run in parallel and therefore invoke function calls in parallel.

**Comment by zdmay** [comment]
pgc mode only works with pyOptSparse's implementation of finite differences
