### ISSUE TITLE
Pass correct optimization name to SNOPT

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#48]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Bugfix (non-breaking change which fixes an issue)

## Description
In many optimizations with SNOPT several strings are not passed in correctly. This includes
- Optimization name
- Objective
- RHS
- Ranges
- Bounds

The main problem with this is that it oftentimes causes encoding problems in the `SNOPT_print.out` file. This makes it difficult to parse or diff in post-processing.

### Code version (if relevant)
**External dependencies:** SNOPT v7.2 and v7.7

**Comment by johnjasa** [comment]
How tough is this to fix? 1 hour, 10 hours? The fix would nominally be backwards compatible?

**Comment by nwu63** [comment]
Not sure but it's probably a memory allocation/passing issue when interfacing with the Fortran routines. I would guess like an hour or two unless the interface files need to be changed which would take longer.

Yes I don't anticipate any backwards incompatibility here.
