### ISSUE TITLE
Issue with OptView not plotting snopt.hist results

### ISSUE THREAD

**Issue by michK** [mdolab/pyoptsparse#58]
Good day,

I am having a problem using OptView to plot the convergence of a problem I am solving with SNOPT.

This used to work fine in the past, but now when I run `python ~/pyoptsparse/postprocessing/OptView.py snopt.hist` I get the error:

```
Traceback (most recent call last):
  File "/home/michael/pyoptsparse/postprocessing/OptView.py", line 1310, in <module>
    disp = Display(histList, outputDir, figsize)
  File "/home/michael/pyoptsparse/postprocessing/OptView.py", line 108, in __init__
    self.OptimizationHistory()
  File "/home/michael/pyoptsparse/postprocessing/OptView_baseclass.py", line 149, in OptimizationHistory
    nkey = int(db['last']) + 1
  File "/home/michael/anaconda3/lib/python3.6/site-packages/sqlitedict.py", line 245, in __getitem__
    raise KeyError(key)
KeyError: 'last'
```
Is this an error anyone here has seen?

PS: I am using the latest v1.0 release and rebuilt after pulling the latest codebase, but the problem initially began quite randomly, i.e. not right after I pulled from the repo or anything like that.

**Python version:** Python 3.6.5 (Anaconda version)

**Comment by michK** [comment]
Hi John,

See attached.
[snopt.zip](https://github.com/mdolab/pyoptsparse/files/3799058/snopt.zip)

Thank you very much!
Michael

**Comment by johnjasa** [comment]
That history file appears to have no data in it, despite having a non-zero filesize. Not sure why that is. Can you share the script you're using to produce this file? You mentioned it fails randomly, does it sometimes work and sometimes it doesn't?

**Comment by michK** [comment]
Interesting.

Unfortunately my program isn't very portable and makes use of various frameworks, so I can't really share it too easily.

And yes initially it was random, but now it seems to be a constant issue.

I'm guessing it's something related to SNOPT, because SNOPT creates that file right?

Michael

**Comment by johnjasa** [comment]
Gotcha. The file is produced by PyOptSparse, so it shouldn't be a SNOPT
versioning issue.

If you run this example:
https://github.com/mdolab/pyoptsparse/blob/master/examples/hs015.py with
`python hs015.py --storeHistory=1` can you read the resulting file with
OptView?

**Comment by michK** [comment]
Yes, that works fine for me.

In that case, I guess it's related to how I set up pyOptSparse in my framework.

I'll do a bit of digging and see if I can find something, and I'll close this issue since it doesn't seem like the problem is related to pyOptSparse itself.

Thanks a lot for your help!
Michael

**Comment by johnjasa** [comment]
Got it, best of luck!
