### ISSUE TITLE
SNOPT tests are broken in latest commit

### ISSUE THREAD

**Issue by dhill2522** [mdolab/pyoptsparse#79]
## Type of issue
What types of issue is it?
- Breaking change (non-backwards-compatible fix or feature)

## Description
One of the latest commits seems to have broken support for the SNOPT optimizer. Any time the optimizer is called it segfaults. Note that commit 91909c4eb0955d10bdba940a0a78fae0c897249a from Feb 5 seems to work fine.

### Steps to reproduce issue
1. Pull the latest commit.
2. Add the files for SNOPT7 to the `pyoptsparse/pySNOPT/source` folder as per installation instructions.
3. Run `python setup.py install --user` from the root of the repository.
4. Run `testflo .` from the root of the repository. All the tests using SNOPT will segfault.

### Current behavior
Current fresh clone and build breaks when running SNOPT optimizer. 

### Expected behavior
Expected SNOPT tests to run properly.

### Code version (if relevant)
**Python version:** 3.7.6

**External dependencies:** As listed in `requirements.txt`

**Internal packages:**

**Comment by dhill2522** [comment]
Mentioning @nsdcoop here as he also has been having this problem and would like to be kept up to date on progress.

Thanks for the great package!

**Comment by nwu63** [comment]
Hi Daniel, what version of SNOPT are you using? As explained in the v2.0 release, the code is now no longer backwards compatible with SNOPT v7.2. As we only have access to v7.7, it's not clear whether the intermediate versions work or not. 

It's actually not too difficult to make the new code work with older SNOPT versions, but I don't have time to work on it and test/verify. Basically, the fortran routine `snkerc` has its function signature changed between v7.2 and v7.7, so if you want you can basically generate the f2py `.pyf` file for that routine. Making the code work for *both* SNOPT versions however would require some logic in the `setup.py` file. As an open source project outside contributions are always welcome. On the other hand, you can always just checkout the latest v1.x tag and use that with v7.2, but obviously you will not receive any new features.

**Comment by dhill2522** [comment]
Ah, I did not realize there was no support for SNOPT 7.2 anymore. I am actually not certain which version I am using, so let me figure that out and get back to you. Given what you said I am guessing it is version 7.2.

Thanks for the help.

**Comment by robfalck** [comment]
As a data point I can confirm that 2.0 doesn't work with SNOPT 7.5.

**Comment by nwu63** [comment]
Right, we were aware of this breaking backwards compatibility with older SNOPT versions, and we understand that many people are still using older versions. Like I said, the fix is probably pretty straightforward, I just don't have the bandwidth to do it. We'd have to generate a different `pyf` file for older versions, and have `f2py` use the appropriate one, maybe based on a user-set environment variable or a flag or something.

**Comment by dhill2522** [comment]
I just confirmed that my version is indeed 7.2, so sorry I reported this as a bug. I must have been looking at an older version of the docs that indicated 7.2 was supported.

I am not certain I have the expertise or time to address this myself, but if it becomes a big issue for my group maybe I will look into it. Right now 1.x is probably just fine. 

Thanks again.
