### ISSUE TITLE
Constraint number in snopt print out

### ISSUE THREAD

**Issue by yqliaohk** [mdolab/pyoptsparse#85]
What types of issue is it?
- New feature (non-breaking change which adds functionality)

## Description
It seems that currently the constraint order in the snopt output does not necessarily match with the order in optProb. When the snopt gives the message that largest discrepancy in a certain constraint number, it's confusing which constraint it's talking about. It might be helpful if we can figure out a way to relate to the information from snopt to the actual constraint.

**Comment by yqliaohk** [comment]
Now we know that the constraint number starts after all variables, maybe we can close this? Or do you have something else in mind to do on this issue? @nwu63

**Comment by nwu63** [comment]
Nope I think we can close this now.
