### ISSUE TITLE
Update IPOPT version

### ISSUE THREAD

**Issue by nwu63** [mdolab/pyoptsparse#88]
The latest version of IPOPT supported is v3.11.7, which is from December 2013, more than six years ago. pyOptSparse should update its python interface to support the latest release.

**Comment by dhill2522** [comment]
This would be greatly appreciated as it is somewhat difficult to build the old version of IPOPT.

**Comment by nwu63** [comment]
Yeah it's on my TODO list but I have plenty of other things on my plate. If you can figure it out we always welcome PRs.

**Comment by dhill2522** [comment]
That certainly makes sense. I would be interested in trying, but to be honest I have not been able to successfully build any version of IPOPT for pyOptSparse, so it is difficult to know exactly where to start.

**Comment by nwu63** [comment]
The instructions in the docs work for the version specified there. We build and test pyOptSparse against IPOPT as part of our testing framework, so it definitely works. IPOPT in general is tricky to install because you need to obtain a linear solver yourself and install it together with the rest of the code.

**Comment by dhill2522** [comment]
Hmm. I have tried several times with no luck, but maybe I am just getting the wrong Ipopt tar file. I am currently trying the one [here](https://github.com/coin-or/Ipopt/archive/releases/3.11.7.tar.gz), but it does not have any `ThirdParty` folder as indicated in the docs. I also tried fetching Ipopt with coinbrew, but ran into the same issue. 

I have the HSL solvers, but making the `ThirdParty` folder myself seems wrong as there are apparently supposed to be scripts already in there.

I tried building Ipopt 3.11.7 separately, but I could never find the "HSLold" required.

Is there something I am missing?

**Comment by nwu63** [comment]
The one we use is [here](https://www.coin-or.org/download/source/Ipopt/Ipopt-3.11.7.tgz)

**Comment by dhill2522** [comment]
Thanks! That solves my problem. Apparently the version you use is quite different than the one found in the Releases tab of the IPOPT GitHub page. 

Just so you are aware, the link in the current docs still points to the GitHub page rather than the coin-or site that you referenced above, which might be misleading.

**Comment by nwu63** [comment]
Oh you're right about that. I will fix it in a PR. Yeah I'm not sure why the versions differ, but the one I linked works for our code.
